#ifndef BINDINGS_LOCATIONS_H
#define BINDINGS_LOCATIONS_H

// we use the following static mapping for the texture units
enum CG2TextureUnitMappings {
	CG2_TEXTURE_UNIT_ALBEDO_MAP=0,
	CG2_TEXTURE_UNIT_NORMAL_MAP=1,
	CG2_TEXTURE_UNIT_MATERIAL_MAP=2,
	CG2_TEXTURE_UNIT_DISPLACEMENT_MAP=3,

	CG2_TEXTURE_UNIT_SKY_MAP=4,
};


// the binding points we are use for the UBOs
enum CG2UBOBindings {
	CG2_UBO_SKINNING_DATA = 0,
	CG2_UBO_CAMERA_DATA = 1,
	CG2_UBO_OBJECT_DATA = 2,
	CG2_UBO_MATERIAL_DATA = 3,
	CG2_UBO_GLOBAL_LIGHT_DATA = 4,
	CG2_UBO_SSAO_KERNEL_DATA = 5,
	CG2_UBO_POST_PROCESSING_DATA = 6,
	CG2_UBO_PROC_TEXTURE_DATA = 7,
	CG2_UBO_LIGHT_EFFECT_CONTROL_DATA = 8,
};




#endif // BINDINGS_LOCATIONS_H
